server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.1.132:8848 #配置Nacos地址
        #切换为nginx的1111端口，做集群
        server-addr: 192.168.1.132:1111 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'